name: tca_flutter
description: "Flutter TCA"
version: 0.0.1
homepage: https://github.com/tisohjung/flutter-dart

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  uuid: ^4.5.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0